# Site settings
title: Epistemology of Agile Development
motto: If you stare into waterfall, waterfall stares back at you
email: info@nicolasweinhold.de
description: > # this means to ignore newlines until "baseurl:"
  Musings about software development, product management and random things that grab my attention.
url: "https://anreizstruktur.github.io" # the base hostname & protocol for your site
twitter_username: anreizstruktur
github_username:  anreizstruktur
# Build settings
markdown: kramdown
